services:
  plex:
    image: plexinc/pms-docker
    container_name: Plex
    healthcheck:
      test: ["CMD-SHELL", "curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
    environment:
      - VERSION=latest
      - TZ=Europe/Amsterdam
      - HOME=/config
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - "32400:32400"
    volumes:
      - ${VOLUMEDIR}/plex:/config:rw
      - ${VOLUMEDIR}/plex:/transcode:rw
      - ${MEDIADIR}:/data:rw
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      # Old Plex router (insecure)
      - "traefik.http.routers.plex-insecure.rule=Host(`plex.home.local`)"
      - "traefik.http.routers.plex-insecure.entrypoints=web"
      - "traefik.http.routers.plex-insecure.service=plex"
      # Plex router (secure)
      - "traefik.http.routers.plex.rule=Host(`plex.home.alborworld.com`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=cloudflare"
    restart: always